apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: telliot-m
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: telliot-m
  labels:
    app: telliot-m
spec:
  serviceName: telliot-m
  replicas: 1
  selector:
    matchLabels:
      app: telliot-m
  template:
    metadata:
      labels:
        app: telliot-m
    spec:
      containers:
      - name: telliot-m
        image: tellor/telliot:latest
        imagePullPolicy: Always
        args: ["mine"]
        ports:
        - name: telliot-m
          containerPort: 9090
        volumeMounts:
        - name: configs
          mountPath: "/configs"
        - name: db
          mountPath: "/db"
        env:
        - name: NODE_URL
          valueFrom:
            secretKeyRef:
              name: telliot-m
              key: NODE_URL
        - name: ETH_PRIVATE_KEYS
          valueFrom:
            secretKeyRef:
              name: telliot-m
              key: ETH_PRIVATE_KEYS
        - name: VIXEOD_KEY
          valueFrom:
            secretKeyRef:
              name: telliot-m
              key: VIXEOD_KEY
        - name: CMC_KEY
          valueFrom:
            secretKeyRef:
              name: telliot-m
              key: CMC_KEY
        - name: RAPID_KEY
          valueFrom:
            secretKeyRef:
              name: telliot-m
              key: RAPID_KEY
        - name: ANYBLOCK_KEY
          valueFrom:
            secretKeyRef:
              name: telliot-m
              key: ANYBLOCK_KEY
      volumes:
      - name: configs
        configMap:
          name: telliot-m
      - name: db
        persistentVolumeClaim:
          claimName: telliot-m
---
kind: Service
apiVersion: v1
metadata:
  name: telliot-m
  labels:
    app: telliot-m
spec:
  selector:
    app: telliot-m
  ports:
  - name: telliot-m
    port: 9090
    targetPort: telliot-m
