apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: telliot-main
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: telliot-main
  labels:
    app: telliot-main
spec:
  serviceName: telliot-main
  replicas: 1
  selector:
    matchLabels:
      app: telliot-main
  template:
    metadata:
      labels:
        app: telliot-main
    spec:
      containers:
      - name: telliot-main
        image: tellor/telliot:master
        imagePullPolicy: Always
        args: ["mine"]
        ports:
        - name: telliot-main
          containerPort: 5000
        volumeMounts:
        - name: configs
          mountPath: "/configs"
        - name: db
          mountPath: "/db"
        env:
        - name: NODE_URL
          valueFrom:
            secretKeyRef:
              name: telliot-main
              key: NODE_URL
        - name: ETH_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: telliot-main
              key: ETH_PRIVATE_KEY
        - name: VIXEOD_KEY
          valueFrom:
            secretKeyRef:
              name: telliot-main
              key: VIXEOD_KEY
      volumes:
      - name: configs
        configMap:
          name: telliot-main
      - name: db
        persistentVolumeClaim:
          claimName: telliot-main
---
kind: Service
apiVersion: v1
metadata:
  name: telliot-main
  labels:
    app: telliot-main
spec:
  selector:
    app: telliot-main
  ports:
  - name: telliot-main
    port: 8080
    targetPort: telliot-main
